var game_file_list = [
	"entity/Obstacle.js",
	"controller/ObjectPool.js",
	"entity/BuffObstacle.js",
	"entity/HotObstacle.js",
	"entity/OverloadObstacle.js",
	"entity/ShakeObstacle.js",
	"controller/ObstacleManager.js",
	"entity/Game.js",
	"NoticeScene.js",
	"UIScene.js",
	"EndScene.js",
	"Main.js",
	"entity/Player.js",
	"entity/Road.js",
	"BitmapMenuItem.js",
	"GameScene.js",
	"LoadingUI.js"
];